apiVersion: v1
kind: Config
users:
- name: system:dns
  user:
    token: "authentication is all open on this cluster, so this can be anything"
clusters:
- name: kubernetes.local
  cluster:
    server: https://10.0.0.1:443
    insecure-skip-tls-verify: true
contexts:
- context:
    cluster: kubernetes.local
    user: system:dns
    namespace: kube-system
  name: service-account-context
current-context: service-account-context
